### ISSUE TITLE
Proposition : 22 avril 22 Démarches Simplifiées avec la DINUM et l'ADULLACT

### ISSUE THREAD

**Issue by mfaure** [blue-hats/ateliers#11]
Démarches Simplifiées (DS) est le logiciel libre pour créer des démarches administratives en ligne. Il offre une utilisation facile et intuitive autant pour l'agent créant la démarche, que le citoyen souhaitant la remplir.

Le logiciel DS compte aujourd'hui trois instances publiques (celle de la DINUM, celle de l'ADULLACT et celle du GIP Territoire Numérique Bourgogne-Franche-Comté )

La DINUM, Direction Interministériel du Numérique est la "DSI de l'État". L'ADULLACT est l'association de collectivités, créée il y a maintenant 20 ans, pour mutualiser les logiciels libre dans les domaines métiers des collectivités.

## Programme prévisionnel

* DS de l'idée initale à aujourd'hui un logiciel reconnu
* Nouveaux besoins, le virage avec les collectivités
* DINUM / ADULLACT : récit d'une collaboration pour un commun numérique

/cc @bzg @krichtof

**Comment by bzg** [comment]
Bonjour @mfaure, avec plaisir pour un atelier sur DS à cette date.  N'hésite pas à faire une PR pour ajouter l'atelier sur `ateliers.org` directement - merci beaucoup !
