### ISSUE TITLE
Proposition : atelier metaverse sur le Web (Mozilla Hubs, Networked AFrame, ImmerSpace)

### ISSUE THREAD

**Issue by Utopiah** [blue-hats/ateliers#21]
On entend parler de metaverse de plus en plus, autant au niveau commercial que plus recemment au niveau legislatif. Derriere ce terme abstrait il existe pourtant deja des implementations et en particuler des implementations libres basees sur des standards et interroperable. Le but de cet atelier et de decouvrir lesquelles, avec quels avantages et limites, et comment les mettre en place.

Mozilla Hubs : solution complete, clef en main, libre et geree par Mozilla.

Networked AFrame : couche uniquement reseau pour qu'un objet en 3D, et potentiellement la voix et la video, puisse s'afficher de facon coherente sur les ordinateurs ou casques VR et AR de tous les participants.

ImmerSpace : couche uniquement federatrice, gestion de profile avec des meta-donnees associes, permettant de connecter plusieurs serveurs avec des implementations independantes e.g Mozilla Hubs, Networked AFrames, FrameVR, etc.

Dedie a tout publique pour l'introduction, en particulier l'architecture, mais pour l'limplementation une maitrise frontend (JavaScript) et backend (NodeJS, containers e.g Docker) necessaire.

Ces outils sont utilise en test (equipe innovation) au Parlement Europeen.

**Comment by bzg** [comment]
Excellente idée, je reviens vers toi par mail.  Merci !

**Comment by Utopiah** [comment]
A voir en gardant https://www.economie.gouv.fr/metavers-premier-grand-rapport-exploratoire en perspective.

**Comment by Utopiah** [comment]
Aie j'avais mal compris il me semblait que nous avions deja bloque une date juste apres FOSDEM. Qu'est-il maintenant encore possible ?

**Comment by Utopiah** [comment]
Relance via https://github.com/blue-hats/ateliers/pull/25

Tres ironique en pensant a https://mastodon.pirateparty.be/@utopiah/109431683050474045 !

**Comment by bzg** [comment]
N'hésite pas à compléter avec une description plus détaillée, merci !

**Comment by Utopiah** [comment]
Seront aussi abordes : 

- atelier RightsCon "Can you host the Metaverse? How learned helplessness from Big Tech made you believe you can’t " https://www.rightscon.org/program/#session-list
- NAF on LAN on RPi0 https://twitter.com/utopiah/status/1646074471378296832
- NAF behinds self-hosted VPNs https://twitter.com/utopiah/status/1646074471378296832/retweets/with_comments
- ThirdRoom/Matrix https://twitter.com/utopiah/status/1651454384440483843
