### ISSUE TITLE
Calendrier Nextcould vide dans README.md ?

### ISSUE THREAD

**Issue by FrancoisSchnell** [blue-hats/ateliers#28]
Sauf erreur de ma part le calendrier Nextcloud proposé dans le README.md semble vide et ne ne pas refléter le contenu d' ateliers.org

"""
## Comment suivre le calendrier ?

Vous pouvez consulter [cette page
web](https://box.bzg.io/cloud/index.php/apps/calendar/p/Lt2cGqsFS82mjkWL)
"""

**Comment by bzg** [comment]
Merci d'avoir signalé ce problème, j'ai retiré le lien vers le calendrier qui n'était plus tenu à jour.
