### ISSUE TITLE
7 mai : Présentation de Open Terms Archive

### ISSUE THREAD

**Issue by clementbiron** [blue-hats/ateliers#3]
_Quel contrat ai-je accepté en utilisant un service numérique ? Les conditions ont-elles changé depuis que j’utilise ces services ? Dans quel sens évoluent-elles ? Sont-elles conformes aux discours de ces acteurs et aux lois qui encadrent leurs pratiques ?_

Un outil simple permet désormais de répondre à ces questions : [Open Terms Archive](http://opentermsarchive.org).

Une présentation par l'équipe de l'ambassadeur pour le numérique.

**Comment by bzg** [comment]
Merci ! Est-ce que la date du 7 mai vous conviendrait ?

**Comment by clementbiron** [comment]
Ok pour nous ✔️
