### ISSUE TITLE
Proposition : Vuejs

### ISSUE THREAD

**Issue by scenaristeur** [blue-hats/ateliers#6]
Bonjour, 
étant dev à la DGFIP, et un peu en dehors, à mes heures perdues, j'ai fait deux tutos pour prendre en main Vuejs https://github.com/vuejs/vuejs.org/blob/master/LICENSE.

Vuejs permet d'avoir un prototype d'application Web en quelques heures.

Je mettrais les liens depuis chez moi, si ça vous intéresse, je ne peux pas depuis le bureau

**Comment by bzg** [comment]
Bonjour,

merci pour votre proposition !  Avec plaisir soit pour partager les liens vers vos tutoriels dans la [gazette BlueHats](https://disic.github.io/gazette-bluehats/a-propos/) soit pour organiser un atelier BlueHats sur `vuejs`, soit pour les deux.

Si vous voulez organiser un atelier, quelle date vous conviendrait ?  Ils sont calés en général les vendredi à 11h.

**Comment by scenaristeur** [comment]
Bonjour @bzg 

- pour commencer, l'installation de l'environnement NodeJs https://youtu.be/KvzmOlxaAWo
- ensuite, j'enchaîne sur un premier composant Vuejs https://youtu.be/_2cZ3u7jznc

Je m'intéresse aussi beaucoup au projet Solid de Tim Berners Lee ( décentralisation, Interopérabilité, Linked Data et Web sémantique) --> https://solidproject.org/ et le forum https://forum.solidproject.org/
ce projet permet de décoreller les données des applications...

donc dans la foulée j'ai un autre tuto pour utiliser cette plateforme et poster des photos sur son Pod Solid https://dfaveris.medium.com/portfolio-comment-cr%C3%A9er-une-application-web-portfolio-bas%C3%A9e-sur-solid-avec-vue-js-c57b50502d21 qui peut également servir pour savoir comment héberger gratuitement une appli Vuejs sur les pages github

ma dernière appli pour une amie https://youtu.be/yV1Z4Sfvebo pour stocker et partager ses favoris/bookmarks sur un Pod Solid

et tant que l'on y est un systeme de mindmap au format Web sémantique s'appuyant lui aussi sur Solid https://youtu.be/IHOVtFjX4lI

Si un atelier vuejs / solid vous intéresse, on peut effectivement caler ça ;-)

+ en lien avec l'assemblée virtuelle https://www.virtual-assembly.org/par-dela-les-silos-part-1/ et prenant part au projet SITI https://wiki.resilience-territoire.ademe.fr/wiki/SITI

**Comment by bzg** [comment]
Hello, merci pour ces propositions ! Tout à fait partant pour les deux ateliers : 

Pour chaque proposition, pouvez-vous ouvrir une issue dédiée avec: 

- une proposition de date (un vendredi de 11h à 12h30)
- un descriptif de ce qu'abordera l'atelier
- le public ciblé et les prérequis
- la liste des intervenants

Pour Solid, c'est top si vous le faite avec quelqu'un de l'Assemblée virtuelle -- et peut-être quelqu'un de chez https://startinblox.com?

Pour Solid, en fonction de la proposition, je pourrai lancer un appel pour qu'une personne connaissant bien vuejs puisse proposer d'intervenir sur d'autres aspects dans une deuxième partie d'atelier.

Merci beaucoup !
